stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - laptop_data.csv
      - params.yaml
    outs:
      - data/raw/train_data.csv
      - data/raw/test_data.csv

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/train_data.csv
      - data/raw/test_data.csv
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv

  model_training:
    cmd: python src/model_trainer.py
    deps:
      - src/model_trainer.py
      - data/processed/train_processed.csv
      - params.yaml
    outs:
      - models/model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - data/processed/test_processed.csv
      - models/model.pkl
    outs:
      - metrics/evaluation.yaml


  register_model:
    cmd: python src/register_model.py
    deps:
      - models/model.pkl
      - metrics/evaluation.yaml
      - src/register_model.py